import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {setBoundary,parcelId,coordinates,inTurkey,validParcel,parcel,zoneFor,features,makeState,applyAction,ZONES,canBuild} from '../src/land.js';
setBoundary(JSON.parse(readFileSync(new URL('../public/data/turkey.json',import.meta.url))));
function find(predicate){for(let x=16400;x<16800;x+=2)for(let y=19300;y<19700;y+=2){const id=`TR-${x}-${y}`,p=parcel(id);if(predicate(p)&&validParcel(id))return id;}throw Error('fixture not found');}
const field=find(p=>p.zone==='field'),home=find(p=>p.zone==='home2'),commercial=find(p=>p.zone==='mixed');
test('fixed parcels reproduce IDs and reject water, foreign land and malformed input',()=>{const id=parcelId(32.8597,39.9334),p=coordinates(id);assert.equal(parcelId(p.lon,p.lat),id);assert.ok(validParcel(id));assert.equal(inTurkey([29,35]),false);assert.equal(validParcel(parcelId(23,38)),false);assert.equal(validParcel('__proto__'),false);assert.equal(validParcel('TR-NaN-NaN'),false);});
test('agricultural zoning forbids houses and commercial premises',()=>{const s=makeState();s.balance=100000;applyAction(s,'a','buy',field);const before=JSON.stringify(s);assert.throws(()=>applyAction(s,'a','build',field,{type:'home'}));assert.equal(JSON.stringify(s),before);assert.throws(()=>applyAction(s,'a','build',field,{type:'cafe'}));applyAction(s,'a','build',field,{type:'farm'});assert.equal(s.holdings[field].building,'farm');});
test('residential floor limits and commercial permissions enforced',()=>{const s=makeState();s.balance=100000;applyAction(s,'a','buy',home);applyAction(s,'a','build',home,{type:'home'});applyAction(s,'a','upgrade',home);assert.equal(s.holdings[home].level,2);assert.throws(()=>applyAction(s,'a','upgrade',home));assert.equal(canBuild(parcel(home),'shop'),false);applyAction(s,'a','buy',commercial);applyAction(s,'a','build',commercial,{type:'cafe'});assert.equal(s.holdings[commercial].building,'cafe');});
test('ownership, insufficient funds and resale use authoritative prices',()=>{const s=makeState();s.balance=0;assert.throws(()=>applyAction(s,'a','buy',home));s.balance=100000;const result=applyAction(s,'a','buy',home,{price:1});assert.equal(result.cost,parcel(home).value);assert.throws(()=>applyAction(s,'b','build',home,{type:'home'}));assert.throws(()=>applyAction(s,'b','buy',home));applyAction(s,'a','list',home,{price:2000});const sale=applyAction(s,'b','buy',home);assert.equal(sale.seller,'a');assert.equal(sale.cost,2000);assert.equal(s.holdings[home].owner,'b');assert.equal(s.holdings[home].listing,null);});
test('rumors can resolve in approval or rejection, with no early building rights',()=>{for(const approved of [true,false]){const id=find(p=>p.base==='field'&&p.approved===approved),z=zoneFor(id);assert.equal(parcel(id,z.review-1).zone,'field');const next=parcel(id,z.review);assert.equal(next.zone,approved?'home3':'field');if(approved)assert.ok(next.value>parcel(id,0).value);}});
test('large viewports are bounded; local grids contain only valid unique parcels',()=>{assert.equal(features([26,36,45,42],0,{}),null);const fc=features([32.855,39.93,32.865,39.94],0,{});assert.ok(fc.features.length>0);assert.equal(new Set(fc.features.map(f=>f.id)).size,fc.features.length);assert.ok(fc.features.every(f=>validParcel(f.id)));});
test('81 province records and district coordinate bounds',()=>{const cities=JSON.parse(readFileSync(new URL('../public/data/places.json',import.meta.url)));assert.equal(cities.length,81);for(const c of cities){assert.ok(c.longitude>25&&c.longitude<45&&c.latitude>35&&c.latitude<43);assert.ok(c.towns.length);}});
