import {HOME_MODELS} from './home-models.js';
import {createWorld} from './world.js';
export function mountHomePicker(root,{free,cost,risky,balance,onBuild}){
 let selected=0,preview;
 root.innerHTML=`<h2>İlk evinin kapısını aç.</h2><p>24 pastel tasarımdan birini seç. Hepsi Level 1 olarak başlar.</p><div class="home-preview"></div><p class="home-name"></p><div class="home-catalog">${HOME_MODELS.map(m=>`<button data-model="${m.id}" aria-pressed="${m.id===0}">🏡 ${m.name}</button>`).join('')}</div><p>${free?'<strong>İlk konutun ücretsiz.</strong> Bu hak hesap başına bir kez kullanılır.':`İnşa bedeli: <strong>${cost} jeton</strong>.`}</p>${risky?'<div class="home-risk"><strong>⚠️ İmarsız yapı · %25 yıkım ihtimali</strong><p>Bu oyunda inşaat tamamlanırken bir kez denetim yapılır. %25 ihtimalle konut yıkılır ve bu parselde 4 gün hiçbir yeni yapı kurulamaz. Ücretsiz hak kullanılmış sayılır; ücretli inşaatta harcanan jeton geri verilmez. Yükseltmede yeniden denetim yapılmaz.</p><label><input type="checkbox" id="home-risk-accept"> Yıkım ihtimalini ve bekleme süresini kabul ediyorum.</label></div>':''}<p class="source-note">Seviye 1–5 · Yükseltme 45 jetondan başlar. Seviye geliştikçe mimari detaylar artar; kat sayısı oyun imar iznini aşmaz. İmarsız konut tek katlı kalır.</p><button class="primary" id="build-selected-home">${free?'Ücretsiz konutumu yap':cost+' jetonla inşa et'}</button><p class="source-note">Konut, parselin gösterilen oyun değerine her seviyede 60 jeton ekler. Bu değer satış veya kazanç garantisi değildir.</p>`;
 const name=root.querySelector('.home-name'),button=root.querySelector('#build-selected-home'),check=root.querySelector('#home-risk-accept');
 function update(){name.textContent=HOME_MODELS[selected].name;root.querySelectorAll('[data-model]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.model)===selected)));button.disabled=balance<cost||(risky&&!check.checked);preview?.render({plots:[{id:1,x:0,z:0,type:'home',level:1,homeModel:selected,homeFloors:1}]});}
 try{preview=createWorld(root.querySelector('.home-preview'),()=>{});update();preview.focus(1);preview.zoom(.45);}catch{root.querySelector('.home-preview').textContent='Bu cihazda 3D önizleme açılamadı. Modelini isim listesinden seçebilirsin.';update();}
 root.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.model);update();});check?.addEventListener('change',update);
 button.onclick=()=>onBuild({type:'home',model:selected,expectedCost:cost,acceptRisk:!!check?.checked});
 root.closest('dialog')?.addEventListener('close',()=>preview?.dispose(),{once:true});
}
