// Synthetic game parcels on a fixed geographic grid. Never cadastral data.
export const CELL=.002;
export const ZONES={field:{name:'Tarla',color:'#b9c583',floors:0,commercial:false,multiplier:1},home2:{name:'Konut · 2 kat',color:'#b8cfe4',floors:2,commercial:false,multiplier:2.1},home3:{name:'Konut · 3 kat',color:'#8eafd0',floors:3,commercial:false,multiplier:2.8},home5:{name:'Konut · 5 kat',color:'#ac9dcc',floors:5,commercial:false,multiplier:3.7},mixed:{name:'Ticaret + konut',color:'#d9b087',floors:5,commercial:true,multiplier:4.4}};
export const BUILDINGS={farm:{name:'Tarım bahçesi',icon:'🌾',cost:600,kind:'farm'},home:{name:'Konut',icon:'🏡',cost:1400,kind:'home'},cafe:{name:'Mahalle kafesi',icon:'☕',cost:1800,kind:'commercial'},shop:{name:'Dükkan',icon:'🏪',cost:2200,kind:'commercial'},fuel:{name:'Benzin istasyonu',icon:'⛽',cost:3200,kind:'commercial'}};
export const HOTSPOTS=[{name:'İstanbul',loc:[28.9784,41.0082]},{name:'İzmir',loc:[27.1428,38.4237]},{name:'Ankara',loc:[32.8597,39.9334]},{name:'Antalya',loc:[30.7133,36.8969]},{name:'Bodrum',loc:[27.4292,37.0344]},{name:'Trabzon',loc:[39.719,41.0027]},{name:'Gaziantep',loc:[37.3781,37.0662]},{name:'Diyarbakır',loc:[40.218,37.9144]}];
let polygons=[];
export function setBoundary(feature){const g=feature.geometry;polygons=(g.type==='Polygon'?[g.coordinates]:g.coordinates).map(rings=>({rings,bounds:rings[0].reduce((b,p)=>[Math.min(b[0],p[0]),Math.min(b[1],p[1]),Math.max(b[2],p[0]),Math.max(b[3],p[1])],[180,90,-180,-90])}));}
function inRing([x,y],ring){let yes=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const [xi,yi]=ring[i],[xj,yj]=ring[j];if(((yi>y)!==(yj>y))&&(x<(xj-xi)*(y-yi)/(yj-yi)+xi))yes=!yes;}return yes;}
export function inTurkey(point){return polygons.some(({rings,bounds:b})=>point[0]>=b[0]&&point[0]<=b[2]&&point[1]>=b[1]&&point[1]<=b[3]&&inRing(point,rings[0])&&!rings.slice(1).some(r=>inRing(point,r)));}
export function hash(s){let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0;}
export function parcelId(lon,lat){return `TR-${Math.floor(lon/CELL)}-${Math.floor(lat/CELL)}`;}
export function coordinates(id){if(!/^TR-\d{5}-\d{5}$/.test(id))throw Error('Geçersiz dijital parsel.');const [,x,y]=id.split('-').map((s,i)=>i?Number(s):s);return {x,y,lon:(x+.5)*CELL,lat:(y+.5)*CELL};}
export function ringFor(id,inset=0){const {x,y}=coordinates(id),a=x*CELL,b=y*CELL,d=CELL;return [[a+inset,b+inset],[a+d-inset,b+inset],[a+d-inset,b+d-inset],[a+inset,b+d-inset],[a+inset,b+inset]];}
export function validParcel(id){try{const c=coordinates(id);return inTurkey([c.lon,c.lat])&&ringFor(id).every(inTurkey);}catch{return false;}}
export function epochWeek(now=Date.now()){return Math.max(0,Math.floor((now-Date.UTC(2026,8,13))/(7*86400000)));}
export function zoneFor(id,week=0){const c=coordinates(id),district=`${Math.floor(c.x/7)}:${Math.floor(c.y/7)}`,h=hash(district),base=['field','field','home2','home3','home5','mixed'][h%6],review=2+h%5,approved=h%3===0;return {key:base==='field'&&week>=review&&approved?'home3':base,base,review,approved,district};}
export function parcel(id,week=0,holdings={}){const {lon,lat}=coordinates(id),h=hash(id),z=zoneFor(id,week);const area=Math.round(6371008.8**2*(CELL*Math.PI/180)*(Math.sin((lat+CELL/2)*Math.PI/180)-Math.sin((lat-CELL/2)*Math.PI/180)));const locationBonus=HOTSPOTS.reduce((v,c)=>Math.max(v,Math.max(0,1-Math.hypot((lon-c.loc[0])*85,(lat-c.loc[1])*111)/30)),0);const raw=320+(h%300)+locationBonus*800;const value=Math.round(raw*ZONES[z.key].multiplier);return {id,lon,lat,area,zone:z.key,value,...z,...holdings[id]};}
export function rumor(p,week){if(p.base!=='field')return {title:'Yürürlükteki oyun planı',text:`Bu dijital bölgede ${ZONES[p.zone].name.toLocaleLowerCase('tr')} izni var. Gerçek belediye planı değildir.`,state:'Kesin oyun kuralı'};if(week<p.review)return {title:'Köy kahvesinde konuşuluyor…',text:`“Yakında buraya imar gelebilirmiş.” Oyun planı ${p.review+1}. haftada incelenecek. Kabul de ret de mümkün. Söylenti yapı izni vermez.`,state:'Doğrulanmamış oyun söylentisi'};return {title:p.approved?'Oyun planı onaylandı':'Oyun planı ertelendi',text:p.approved?'Bu bölge oyun içinde üç kat konut izni aldı. Yeni değer ve yapı hakları uygulanıyor.':'Başvuru oyun içinde kabul edilmedi. Tarla niteliği ve yapı yasağı devam ediyor.',state:'Oyun kararı'};}
export function canBuild(p,type){return !!BUILDINGS[type]&&(type==='farm'?p.zone==='field':type==='home'?ZONES[p.zone].floors>0:ZONES[p.zone].commercial);}
export function upgradePrice(p){return 1000*(p.level||1);}
export function applyAction(state,user,action,id,data={}){if(!validParcel(id))throw Error('Bu dijital parsel Türkiye kara sınırı içinde değil.');const p=parcel(id,state.week,state.holdings);let cost=0,seller=null;if(action==='buy'){if(p.owner===user)throw Error('Bu parsel zaten senin.');if(p.owner&&!p.listing)throw Error('Bu parsel satışta değil.');cost=p.listing||p.value;seller=p.owner;}else{if(p.owner!==user)throw Error('Bu parsel sana ait değil.');if(action==='build'){if(p.building)throw Error('Bu parselde zaten bir yapı var.');if(!canBuild(p,data.type))throw Error('Oyun imar planı bu yapıya izin vermiyor.');cost=BUILDINGS[data.type].cost;}else if(action==='upgrade'){if(!p.building||p.building==='farm'||p.level>=ZONES[p.zone].floors)throw Error('İzin verilen kat sınırına ulaştın.');cost=upgradePrice(p);}else if(action==='list'){if(!Number.isSafeInteger(data.price)||data.price<100||data.price>1000000)throw Error('100–1.000.000 arasında tam sayı gir.');}else if(action!=='unlist')throw Error('Geçersiz işlem.');}if(state.balance<cost)throw Error('Yeterli oyun jetonu yok.');state.balance-=cost;const owned={...state.holdings[id]};if(action==='buy'){owned.owner=user;owned.listing=null;}if(action==='build'){owned.building=data.type;owned.level=data.type==='farm'?0:1;}if(action==='upgrade')owned.level++;if(action==='list')owned.listing=data.price;if(action==='unlist')owned.listing=null;state.holdings[id]=owned;state.revision=(state.revision||0)+1;return {cost,seller,p:parcel(id,state.week,state.holdings)};}
export function makeState(){return {version:2,holdings:{},balance:15000,week:0,revision:1};}
export function features(bounds,week,holdings,limit=2200){const [west,south,east,north]=bounds,minX=Math.floor(Math.max(25.5,west)/CELL),maxX=Math.floor(Math.min(45,east)/CELL),minY=Math.floor(Math.max(35.7,south)/CELL),maxY=Math.floor(Math.min(42.3,north)/CELL);if((maxX-minX+1)*(maxY-minY+1)>limit)return null;const out=[];for(let x=minX;x<=maxX;x++)for(let y=minY;y<=maxY;y++){const id=`TR-${x}-${y}`;if(!validParcel(id))continue;const p=parcel(id,week,holdings);out.push({type:'Feature',id,geometry:{type:'Polygon',coordinates:[ringFor(id,.000035)]},properties:{id,color:ZONES[p.zone].color,zone:p.zone,owner:p.owner||'',listing:p.listing||0,height:p.building&&p.building!=='farm'?p.level*9:0}});}return {type:'FeatureCollection',features:out};}
