import './style.css';
import {createWorld} from './world.js';
import {TYPES,LEVELS,price,upgradeCost,initialWorld,demoAction} from './game.js';
const $=s=>document.querySelector(s),fmt=n=>new Intl.NumberFormat('tr-TR').format(n),api=import.meta.env.VITE_API_URL?.replace(/\/$/,'');
const icons={map:'<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5Zm6-2v16m6-14v16"/>',home:'<path d="m3 10 9-7 9 7v10H3V10Zm6 10v-7h6v7"/>',shop:'<path d="M4 10v10h16V10M3 10l2-7h14l2 7M9 20v-7h6v7M3 10q3 4 6 0 3 4 6 0 3 4 6 0"/>',leaf:'<path d="M20 3C7 2 2 7 5 15s16 3 15-12ZM5 20 16 8"/>',plus:'<path d="M12 5v14M5 12h14"/>',minus:'<path d="M5 12h14"/>',reset:'<path d="M3 10a9 9 0 1 1 1 8M3 3v7h7"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',rotate:'<path d="M20 10a8 8 0 1 0 0 6M20 3v7h-7"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 8c0-4 7-3 6 1-.5 2-3 2-3 5m0 2v1"/>',wallet:'<rect x="3" y="5" width="18" height="15" rx="3"/><path d="M3 7V4l14-2v3m4 7h-6v4h6"/>',chevron:'<path d="m9 5 7 7-7 7"/>'};
function icon(n){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]||icons.home}</svg>`;}
let state={...initialWorld(),balance:7500},user=null,tab='explore',selected=null,filter='all',busy=false,world;
if(!api){try{const saved=JSON.parse(localStorage.getItem('mahalle-demo-v1'));if(saved&&Array.isArray(saved.plots)&&Number.isFinite(saved.balance))state=saved;}catch{}}
try{user=JSON.parse(sessionStorage.getItem('mahalle-user'));}catch{}
const app=$('#app');app.innerHTML=`
<header class="topbar"><a class="brand" href="./" aria-label="Mahalle ana sayfa"><span class="brand-icon">${icon('home')}</span><span>mahalle<span class="brand-dot">.</span></span></a><nav aria-label="Ana menü"><button class="nav active" data-tab="explore">${icon('map')}<span>Keşfet</span></button><button class="nav" data-tab="market">${icon('shop')}<span>Pazar yeri</span></button><button class="nav" data-tab="mine">${icon('home')}<span>Benim yerlerim</span></button></nav><div class="account"><button class="balance" id="wallet">${icon('wallet')}<span id="balance"></span><span class="add-credit">+</span></button><button id="profile" class="avatar" aria-label="Hesap">H</button></div></header>
<main><section class="map-area" aria-label="Mahalle haritası"><div id="world"></div><div class="map-heading"><div class="eyebrow"><span class="live-dot"></span> BİRLİKTE BÜYÜYEN BİR DÜNYA</div><h1>Küçük bir yer.<br><em>Kocaman hayaller.</em></h1><p>Bir arsa seç. Hayalini kur. Mahalleye hayat kat.</p><div class="world-chips"><span>${icon('leaf')} Yeşilvadi Mahallesi</span><span id="mode">${api?'Ortak mahalle':'Demo mahallesi'}</span></div></div><div class="map-top-right"><button class="circle" id="day" aria-label="Gündüz ve akşam görünümü">${icon('sun')}</button></div><div class="legend"><span><i class="available"></i>Satılık arsa</span><span><i class="owned"></i>Senin yerin</span><span><i class="neighbor"></i>Komşuların</span></div><div class="map-tools"><button id="zoom-in" aria-label="Yakınlaştır">${icon('plus')}</button><button id="zoom-out" aria-label="Uzaklaştır">${icon('minus')}</button><div></div><button id="rotate" aria-label="Haritayı döndür">${icon('rotate')}</button><button id="reset-camera" aria-label="Haritayı ortala">${icon('reset')}</button></div><div class="map-hint"><span class="mouse">↔</span> Sürükle ve keşfet <span>·</span> Yakınlaştırmak için kaydır</div><div class="map-bottom"><div><span class="tiny-houses">${icon('home')}</span><span><strong id="built-count"></strong><small>Birlikte büyüyoruz</small></span></div><button id="help" class="circle" aria-label="Nasıl oynanır?">${icon('help')}</button></div><div class="loading" id="loading"><span class="brand-icon">${icon('home')}</span><p>Mahalle uyanıyor…</p></div></section>
<aside class="sidebar"><div id="side-content"></div><div class="sidebar-footer">Birlikte daha güzel. <span>✳</span></div></aside></main><div id="toast" role="status" aria-live="polite"></div><dialog id="modal"></dialog>`;
function save(){if(!api)try{localStorage.setItem('mahalle-demo-v1',JSON.stringify(state));}catch{toast('Tarayıcı kaydı kapalı. İlerlemen bu oturumda kalacak.');}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
async function request(path,data){const res=await fetch(api+path,{method:data?'POST':'GET',headers:{'Content-Type':'application/json',...(user?.token?{Authorization:'Bearer '+user.token}:{})},...(data?{body:JSON.stringify(data)}:{})});const body=await res.json();if(!res.ok)throw Error(body.error||'İşlem tamamlanamadı.');return body;}
async function refresh(){if(api){const data=await request('/world');state={...data,balance:0};if(user){try{const me=await request('/me');state.balance=me.balance;}catch{user=null;sessionStorage.removeItem('mahalle-user');}}}world?.render(state,api?user?.id:'you');draw();}
function mine(p){return p.owner===(api?user?.id:'you');}
function draw(){
 $('#balance').textContent=fmt(state.balance);$('#profile').textContent=user?user.name.slice(0,1).toUpperCase():'H';$('#built-count').textContent=`${state.plots.filter(p=>p.type).length} yuva, ${state.plots.length} arsa`;
 document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
 const target=$('#side-content');if(selected){detail(target);return;}
 const count=state.plots.filter(p=>!p.owner).length;
 target.innerHTML=`<div class="section-kicker">${tab==='market'?'KOMŞUDAN KOMŞUYA':tab==='mine'?'SENİN HİKÂYEN':'MAHALLEYE HOŞ GELDİN'}</div><h2>${tab==='market'?'Yeni bir yer, yeni bir hikâye.':tab==='mine'?'Hayallerin burada büyüyor.':'Senin hikâyen<br>nerede başlasın?'}</h2><p class="muted">${tab==='market'?'Satışa çıkan yerleri keşfet, yeni komşumuz ol.':tab==='mine'?'Arsalarını yönet, inşa et ve bir sonraki seviyeye taşı.':'Küçük bir çiftlik, sıcacık bir kafe veya gökyüzüne uzanan bir ev. Seçim senin.'}</p>
 ${tab==='explore'?`<div class="welcome-card"><span class="seed">🌱</span><div><strong>Her büyük hayal küçük başlar.</strong><p>İlk arsanı seç, mahallede yerini al.</p></div></div>`:''}
 <div class="list-heading"><h3>${tab==='mine'?'Benim yerlerim':'Bir yer seç'}</h3><span>${tab==='mine'?state.plots.filter(mine).length:count} ${tab==='mine'?'yer':'boş arsa'}</span></div>
 ${tab!=='mine'?`<div class="filters" role="group" aria-label="Arsa filtresi"><button data-filter="all" class="${filter==='all'?'chosen':''}">Tümü</button><button data-filter="land" class="${filter==='land'?'chosen':''}">Arsalar</button><button data-filter="building" class="${filter==='building'?'chosen':''}">Binalar</button></div>`:''}<div id="plot-list"></div>
 <div class="demo-note">${api?'Ortak bir oyun dünyası. Tüm yerler sanaldır.':'Ücretsiz demo · 7.500 oyun jetonu ile dene. Bu cihazdaki ilerlemen kaydedilir. Gerçek ödeme ve ortak oyuncu dünyası henüz açık değil.'}</div>`;
 let list=state.plots.filter(p=>tab==='mine'?mine(p):(!p.owner||p.listing));if(tab!=='mine')list=list.filter(p=>filter==='land'?!p.type:filter==='building'?!!p.type:true);
 $('#plot-list').innerHTML=list.length?list.map(p=>`<button class="plot-card" data-plot="${p.id}"><span class="plot-thumb ${p.type?'house-thumb':''}">${p.type?miniHouse(p.type):'<span class="mini-plot"><i></i>＋</span>'}</span><span class="plot-info"><small>${p.type?'KOMŞUDAN SATILIK':'YENİ BİR BAŞLANGIÇ'}</small><strong>${p.type?TYPES[p.type].name:'Arsa'} <span>#${String(p.id).padStart(3,'0')}</span></strong><span class="location">${location(p)} · ${p.type?'Seviye '+p.level:'400 m²'}</span><span class="plot-price">${mine(p)?'Senin yerin':fmt(p.listing||price(p))+' ◈'} <small>${p.z===0?'Merkez konum':''}</small></span></span><span class="card-arrow">${icon('chevron')}</span></button>`).join(''):`<div class="empty">${icon('home')}<strong>${tab==='mine'?'İlk yerin seni bekliyor.':'Şu anda uygun yer yok.'}</strong><p>${tab==='mine'?'Haritadan bir arsa seçerek başlayabilirsin.':'Başka bir filtre seç veya sonra tekrar bak.'}</p><button class="text-button" id="back-explore">Mahalleye dön ${icon('arrow')}</button></div>`;
 target.querySelectorAll('[data-plot]').forEach(b=>b.onclick=()=>select(+b.dataset.plot));target.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;draw();});$('#back-explore')?.addEventListener('click',()=>{tab='explore';filter='all';draw();});
}
function location(p){return p.z===0?'Meydan Caddesi':p.z<0?'Çınar Sokak':'Papatya Sokak';}
function miniHouse(type){return `<span class="mini-house ${type}"><i class="mini-roof"></i><i class="mini-wall"></i><i class="mini-window"></i><i class="mini-door"></i><i class="mini-tree"></i></span>`;}
function select(id){selected=id;world?.select(id);draw();}
function detail(target){const p=state.plots.find(p=>p.id===selected);if(!p){selected=null;draw();return;}const owned=mine(p),canBuy=!p.owner||p.listing;
 target.innerHTML=`<button class="back" id="back">← Mahalleye dön</button><div class="detail-art ${p.type?'has-house':''}">${p.type?miniHouse(p.type):'<span class="mini-plot"><i></i>＋</span>'}<span>${owned?'SENİN YERİN':canBuy?'YENİ HİKÂYELERE AÇIK':'KOMŞUNUN YERİ'}</span></div><div class="section-kicker">${location(p).toUpperCase()} · #${String(p.id).padStart(3,'0')}</div><h2>${p.type?TYPES[p.type].name:'Burada bir hayal<br>yeşerebilir.'}</h2><p class="muted">${p.type?TYPES[p.type].description:'400 m² büyüklüğünde, yeni komşularını bekleyen bir arsa.'}</p><div class="facts"><div><small>${p.type?'Bina seviyesi':'Konum'}</small><strong>${p.type?p.level+' / 5':p.z===0?'Merkez':'Sakin sokak'}</strong></div><div><small>Sahibi</small><strong>${owned?'Sen':esc(p.ownerName||'Mahalle')}</strong></div></div>
 ${p.type?`<div class="level-track">${[1,2,3,4,5].map(l=>`<i class="${l<=p.level?'filled':''}"></i>`).join('')}</div><p class="level-caption">${LEVELS[p.level]} ${p.level<5?'→ '+LEVELS[p.level+1]:'· En yüksek seviye'}</p>`:''}
 <div id="actions">${owned?(!p.type?`<h3>Ne inşa etmek istersin?</h3><div class="build-grid">${Object.entries(TYPES).map(([k,v])=>`<button data-build="${k}"><span>${v.icon}</span><strong>${v.name}</strong><small>${fmt(v.cost)} ◈</small></button>`).join('')}</div>`:p.level<5?`<button class="primary full" id="upgrade">${icon('plus')} Seviyeyi yükselt <span>${fmt(upgradeCost(p))} ◈</span></button>`:'<p class="achievement">✦ Hayalin gökyüzüne ulaştı!</p>')+(p.listing?`<div class="listing-note">${fmt(p.listing)} ◈ karşılığında satışta.</div><button class="secondary full" id="unlist">İlanı kaldır</button>`:`<button class="secondary full" id="list">${icon('shop')} Satışa çıkar</button>`):canBuy?`<div class="buy-price"><span>${p.type?'Satış fiyatı':'Arsa fiyatı'}</span><strong>${fmt(p.listing||price(p))} <small>◈</small></strong></div><button class="primary full" id="buy">${api?'Satın al':'Demo jetonuyla satın al'} ${icon('arrow')}</button>`:'<div class="welcome-card">Bu yer şu anda satışta değil. Diğer arsaları keşfedebilirsin.</div>'}</div><p class="detail-note">${api?'Oyun jetonları ve sanal mülklerdir.':'Demo modu · Gerçek para kullanılmaz.'}</p>`;
 $('#back').onclick=()=>{selected=null;world?.select(null);draw();};$('#buy')?.addEventListener('click',()=>confirmAction('buy',p.listing||price(p)));$('#upgrade')?.addEventListener('click',()=>confirmAction('upgrade',upgradeCost(p)));target.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>confirmAction('build',TYPES[b.dataset.build].cost,{type:b.dataset.build}));$('#unlist')?.addEventListener('click',()=>act('unlist'));$('#list')?.addEventListener('click',()=>{modal(`<span class="modal-symbol">${icon('shop')}</span><h2>Yeni bir hikâyeye yer aç.</h2><p>Satış fiyatını oyun jetonu olarak belirle.</p><form id="listing-form"><label>Satış fiyatı<input name="price" type="number" min="100" max="1000000" step="1" value="${p.listing||price(p)+(p.type?TYPES[p.type].cost*p.level:0)}" required></label><button class="primary full">İlanı yayınla</button></form><small>${api?'Alıcı ödemesiyle mülkiyet birlikte aktarılır.':'Demo ilanı yalnızca bu cihazda görünür.'}</small>`);$('#listing-form').onsubmit=e=>{e.preventDefault();act('list',{price:Number(new FormData(e.target).get('price'))});};});
}
function modal(html){$('#modal').innerHTML=`<button class="modal-close circle" aria-label="Kapat">${icon('close')}</button>${html}`;$('#modal').querySelector('.modal-close').onclick=()=>$('#modal').close();if(!$('#modal').open)$('#modal').showModal();}
function confirmAction(action,cost,data={}){if(api&&!user){account();return;}modal(`<span class="modal-symbol">${icon(action==='buy'?'home':'plus')}</span><h2>${action==='buy'?'Mahallede yerini al.':action==='build'?'Hayaline ilk tuğlayı koy.':'Biraz daha büyüyelim.'}</h2><p>Bu işlem için <strong>${fmt(cost)} oyun jetonu</strong> kullanılacak.</p><div class="facts"><div><small>Bakiyen</small><strong>${fmt(state.balance)} ◈</strong></div><div><small>İşlem sonrası</small><strong>${fmt(state.balance-cost)} ◈</strong></div></div><button class="primary full" id="confirm-action" ${state.balance<cost?'disabled':''}>${state.balance<cost?'Yetersiz bakiye':'Onayla ve devam et'} ${icon('arrow')}</button><p class="detail-note">${api?'Bu işlem sanal bir oyun içi satın alımdır.':'Ücretsiz demo. Kart veya gerçek ödeme gerekmez.'}</p>`);$('#confirm-action').onclick=()=>act(action,data);}
async function act(action,data={}){if(busy)return;busy=true;const buttons=[...$('#modal').querySelectorAll('button'),...$('#actions').querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{if(api){await request('/action',{action,id:selected,...data});await refresh();}else{demoAction(state,action,selected,data);save();world?.render(state,api?user?.id:'you');draw();}$('#modal').close();toast({buy:'Hoş geldin komşu! Bu yer artık senin. 🌱',build:'Yeni binan mahalleye çok yakıştı!',upgrade:'Binan bir seviye daha büyüdü!',list:'İlanın hazır.',unlist:'İlanın kaldırıldı.'}[action]);}catch(e){toast(e.message);buttons.forEach(b=>b.disabled=false);}finally{busy=false;}}
function account(){if(!api){modal(`<span class="modal-symbol">${icon('home')}</span><h2>Hoş geldin, komşu.</h2><p>Şu an ücretsiz demo mahallesindesin. İlerlemen bu tarayıcıda saklanıyor. Ortak mahalle ve gerçek hesaplar sunucu bağlandığında açılacak.</p><button class="primary full" id="continue-demo">Keşfetmeye devam et</button><button class="text-button reset-demo" id="restart">Demoyu sıfırla</button>`);$('#continue-demo').onclick=()=>$('#modal').close();$('#restart').onclick=()=>{modal('<h2>Yeniden başlayalım mı?</h2><p>Bu cihazdaki demo arsaların, binaların ve ilanların silinecek.</p><button class="primary full" id="really-reset">Evet, demoyu sıfırla</button>');$('#really-reset').onclick=()=>{state={...initialWorld(),balance:7500};selected=null;save();world?.render(state);draw();$('#modal').close();};};return;}if(user){modal(`<h2>Merhaba, ${esc(user.name)}.</h2><p>Ortak mahalledeki yerlerin hesabına bağlıdır.</p><button class="secondary full" id="logout">Çıkış yap</button>`);$('#logout').onclick=async()=>{await request('/logout',{}).catch(()=>{});user=null;sessionStorage.removeItem('mahalle-user');$('#modal').close();await refresh();};return;}modal(`<h2>Mahalleye katıl.</h2><p>Keşfetmek serbest. Kendi yerin için giriş yap.</p><form id="auth-form"><label>İsim (yeni hesap için)<input name="name" maxlength="40" autocomplete="nickname"></label><label>E-posta<input name="email" type="email" autocomplete="email" required></label><label>Şifre<input name="password" type="password" minlength="10" autocomplete="current-password" required></label><button class="primary full" name="mode" value="login">Giriş yap</button><button class="secondary full" name="mode" value="register">Yeni hesap oluştur</button></form>`);$('#auth-form').onsubmit=async e=>{e.preventDefault();const form=Object.fromEntries(new FormData(e.target));e.submitter.disabled=true;try{user=await request('/auth/'+e.submitter.value,form);sessionStorage.setItem('mahalle-user',JSON.stringify(user));$('#modal').close();await refresh();}catch(err){toast(err.message);}finally{e.submitter.disabled=false;}};}
$('#wallet').onclick=()=>{if(!api){modal('<h2>Hayaller için küçük bir destek.</h2><p>Şu an demo modundasın. Gerçek ödeme yapılmaz. Denemeye devam etmek için ücretsiz oyun jetonu ekleyebilirsin.</p><button class="primary full" id="demo-credit">Ücretsiz 5.000 demo jetonu ekle</button>');$('#demo-credit').onclick=()=>{state.balance+=5000;save();draw();$('#modal').close();toast('5.000 demo jetonu eklendi.');};return;}if(!user){account();return;}modal('<h2>Oyun jetonu al.</h2><p>1.000 jeton · 5,00 €<br>Jetonlar yalnızca oyun içindir, nakde çevrilemez.</p><button class="primary full" id="checkout">Stripe ile devam et</button>');$('#checkout').onclick=async e=>{e.target.disabled=true;try{const {url}=await request('/checkout',{});location.href=url;}catch(err){toast(err.message);e.target.disabled=false;}};};
$('#profile').onclick=account;
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;selected=null;filter='all';world?.select(null);draw();});
$('#help').onclick=()=>modal(`<span class="modal-symbol">🌱</span><h2>Bir mahalle, binlerce hikâye.</h2><ol class="instructions"><li><strong>Keşfet.</strong> Haritayı sürükle, bir arsaya dokun. Sağ tuşla haritayı kaydır; telefonda iki parmağını kullan.</li><li><strong>Yerini seç.</strong> Merkezdeki arsalar daha değerlidir.</li><li><strong>İnşa et.</strong> Çiftlik, ev, kafe veya istasyon kur.</li><li><strong>Büyüt.</strong> Beşinci seviyede gökdelene ulaş.</li><li><strong>Paylaş.</strong> Yerini pazarda satışa çıkar.</li></ol><p>${api?'Dünya tüm oyuncular tarafından paylaşılır.':'Demo ilerlemesi bu cihazdadır. Diğer oyuncularla eşzamanlı değildir.'}</p><button class="secondary full" id="pause">Hareketleri durdur / devam ettir</button>`);$('#modal').addEventListener('click',e=>{if(e.target.closest('#pause'))toast(world?.pause()?'Hareketler durduruldu.':'Mahalle yeniden hareketli.');});
$('#zoom-in').onclick=()=>world?.zoom(.8);$('#zoom-out').onclick=()=>world?.zoom(1.2);$('#reset-camera').onclick=()=>world?.reset();$('#rotate').onclick=()=>world?.rotate();$('#day').onclick=()=>world?.night();
draw();try{world=createWorld($('#world'),select);world.render(state);$('#loading').remove();}catch(e){$('#loading').innerHTML='<h2>3D görünüm açılamadı.</h2><p>WebGL destekleyen güncel bir tarayıcı kullan. Sağdaki arsa listesiyle oynamaya devam edebilirsin.</p>';console.error(e);}
if(api){refresh().catch(()=>{toast('Ortak mahalleye bağlanılamadı. Daha sonra tekrar dene.');$('#mode').textContent='Bağlantı yok';$('#side-content').innerHTML='<h2>Mahalleye bağlanılamadı.</h2><p>Sayfayı yenileyerek tekrar dene.</p>';});setInterval(()=>{if(!busy&&!$('#modal').open)refresh().catch(()=>{});},15000);if(new URLSearchParams(location.search).get('payment')==='success')toast('Ödeme kontrol ediliyor. Onaylanınca jetonların hesabına eklenecek.');}
