import './style.css';
import {createMap} from './map.js';
import {setLand,landFeature,setLanduse,parcel,ZONES,BUILDINGS,HOTSPOTS,rumor,canBuild,upgradePrice,makeState,applyAction} from './land.js';
const $=s=>document.querySelector(s),fmt=n=>new Intl.NumberFormat('tr-TR').format(n),api=import.meta.env.VITE_API_URL?.replace(/\/$/,''),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',map:'<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5Zm6-2v16m6-14v16"/>',grid:'<rect x="3" y="3" width="18" height="18" rx="3"/><path d="M3 9h18M3 15h18M9 3v18M15 3v18"/>',home:'<path d="m3 10 9-7 9 7v10H3V10Zm6 10v-7h6v7"/>',shop:'<path d="M4 10v10h16V10M3 10l2-7h14l2 7M9 20v-7h6v7M3 10q3 4 6 0 3 4 6 0 3 4 6 0"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',layers:'<path d="m3 8 9-5 9 5-9 5-9-5Zm0 5 9 5 9-5M3 18l9 5 9-5"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',wallet:'<rect x="3" y="5" width="18" height="15" rx="3"/><path d="M3 7V4l14-2v3m4 7h-6v4h6"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 8c0-4 7-3 6 1-.5 2-3 2-3 5m0 2v1"/>'};
function icon(n){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[n]||paths.pin}</svg>`;}
let state=makeState(),user=null,map,selected=null,tab='explore',filter='all',visible=[],places=[],busy=false,region='Türkiye',available=false;
if(!api)try{const saved=JSON.parse(localStorage.getItem('dijital-arsam-v3'));if(saved?.version===3&&saved.holdings&&Number.isFinite(saved.balance)&&Number.isSafeInteger(saved.week))state=saved;}catch{}
try{user=JSON.parse(sessionStorage.getItem('mahalle-user'));}catch{}
$('#app').innerHTML=`<header><a href="./" class="brand"><span class="brand-mark">${icon('layers')}</span><span>dijital<span class="brand-light">arsam</span><i></i></span></a><nav aria-label="Ana menü"><button data-tab="explore" class="active">${icon('map')} Keşfet</button><button data-tab="market">${icon('shop')} Pazar yeri</button><button data-tab="mine">${icon('grid')} Arsalarım</button></nav><div class="account"><span class="demo-badge">${api?'ORTAK DÜNYA':'DEMO'}</span><button class="wallet" id="wallet">${icon('wallet')} <b id="balance"></b><span>+</span></button><button class="avatar" id="account" aria-label="Hesap">D</button></div></header>
<main><section class="map-panel"><div id="map"></div><div class="map-shade"></div><div class="map-intro"><div class="overline"><i></i> GERÇEK HARİTA. SENİN DİJİTAL DÜNYAN.</div><h1>Türkiye’de bir yer.<br><em>Hayalinde bir gelecek.</em></h1><p>Keşfet, dijital arsanı seç, kendi hikâyeni inşa et.</p></div><div class="search-area"><form id="search-form"><span>${icon('search')}</span><input id="search" placeholder="İl, ilçe veya koordinat ara…" aria-label="İl, ilçe veya enlem boylam ara" autocomplete="off"><button aria-label="Ara">↵</button></form><div id="results" hidden></div><div class="quick-places">${HOTSPOTS.slice(0,5).map((p,i)=>`<button data-hot="${i}">${p.name}</button>`).join('')}</div></div>
<div class="layer-switch" role="group" aria-label="Harita türü"><button class="active" data-mode="satellite">◉ Uydu</button><button data-mode="street">${icon('map')} Sokak</button></div><div class="map-actions"><button id="turkey" title="Türkiye'nin tamamı" aria-label="Türkiye'nin tamamını göster">${icon('map')}</button><button id="grid" aria-label="Parselleri göster veya gizle" aria-pressed="true">${icon('grid')}</button><button id="tilt" aria-label="Üç boyutlu görünüm">3D</button></div><div class="map-status"><span class="pulse"></span><span id="map-status">Türkiye haritası yükleniyor…</span></div><div class="map-legend"><span><i style="background:#b9c583"></i>Tarla · imarsız</span><span><i style="background:#a8c5e0"></i>Konut arsası</span><span><i style="background:#d9b087"></i>Ticaret</span><span><i style="background:#fbe1a2"></i>Seçili</span></div><div class="map-notice">Parsel şekilleri üretilmiştir; imar sınıfı gerçek yerleşim verisinden türetilir. Tapu kaydı değildir.</div><div id="map-error" hidden></div></section>
<aside><div id="side"></div><footer><span>Bir yer seç. Bir gelecek hayal et.</span><button id="help" aria-label="Oyun hakkında">${icon('help')}</button></footer></aside></main><div id="toast" role="status" aria-live="polite"></div><dialog id="modal"></dialog>`;
function save(){if(!api)try{localStorage.setItem('dijital-arsam-v3',JSON.stringify(state));}catch{toast('Tarayıcı kaydı kapalı; ilerlemen bu oturumda kalır.');}}
function mine(p){return p.owner===(api?user?.id:'you');}
function get(id){return parcel(id,state.week,state.holdings);}
function safeGet(id){try{return get(id);}catch{return null;}}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function modal(html){$('#modal').innerHTML=`<button class="close" aria-label="Kapat">${icon('close')}</button>${html}`;$('#modal .close').onclick=()=>$('#modal').close();if(!$('#modal').open)$('#modal').showModal();}
function draw(){
 $('#balance').textContent=fmt(state.balance);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
 if(selected){detail();return;}
 const owned=Object.keys(state.holdings).filter(id=>safeGet(id)&&mine(get(id))),listed=Object.keys(state.holdings).filter(id=>state.holdings[id].listing&&safeGet(id));
 $('#side').innerHTML=`<div class="eyebrow">${tab==='mine'?'DİJİTAL PORTFÖYÜN':tab==='market'?'KOMŞUDAN KOMŞUYA':'YENİ BİR BAŞLANGIÇ'}</div><h2>${tab==='mine'?'Geleceğe ayırdığın<br>küçük yerler.':tab==='market'?'Yeni sahibini<br>bekleyen hikâyeler.':'Bir toprak parçası.<br>Binlerce ihtimal.'}</h2><p class="muted">${tab==='mine'?'Arsalarını yönet, izinlerini incele ve yeni bir şeyler kur.':tab==='market'?'Oyuncuların satışa çıkardığı dijital parselleri keşfet.':'Ege’de bir tarla, şehirde bir arsa… Türkiye’yi yakınlaştır, sana ait bir hikâye başlat.'}</p>
 <div class="season-card"><span class="season-icon">🌱</span><div><strong>${state.week+1}. hafta <span>OYUN TAKVİMİ</span></strong><p>Her bölgenin başka bir ihtimali var.</p></div>${!api?'<button id="next-week" aria-label="Oyun haftasını ilerlet">→</button>':''}</div>
 ${tab==='mine'?`<div class="portfolio-stats"><div><strong>${owned.length}</strong><small>Dijital parsel</small></div><div><strong>${fmt(owned.reduce((n,id)=>n+get(id).value,0))} ◈</strong><small>Tahmini oyun değeri</small></div></div>`:''}
 <div class="list-head"><h3>${tab==='mine'?'Arsalarım':tab==='market'?'Satıştaki parseller':'Görünür parseller'}</h3><span>${tab==='mine'?owned.length:tab==='market'?listed.length:visible.length}</span></div><div class="filters">${['all','field','home','mixed'].map((f,i)=>`<button data-filter="${f}" class="${filter===f?'active':''}">${['Tümü','Tarla','Konut','Ticaret'][i]}</button>`).join('')}</div><div id="parcel-list"></div><div class="source-note">${api?'Ortak dünya · Oyun hakları sunucuda saklanır.':'Ücretsiz demo · İşlemler bu tarayıcıda saklanır. Diğer oyuncularla eşzamanlı değildir.'}</div>`;
 let ids=tab==='mine'?owned:tab==='market'?listed:visible;
 ids=ids.filter(id=>{const p=safeGet(id);return p&&(filter==='all'||filter==='home'&&p.zone.startsWith('home')||p.zone===filter);});
 $('#parcel-list').innerHTML=ids.length?ids.slice(0,30).map(id=>{const p=get(id);return `<button class="parcel-card" data-parcel="${id}"><span class="parcel-art ${p.zone}" style="--parcel:${ZONES[p.zone].color}"><i></i><b>${p.building?BUILDINGS[p.building].icon:p.zone==='field'?'♧':'⌂'}</b></span><span class="card-info"><small>${mine(p)?'SENİN ARSAN':p.listing?'OYUNCU İLANI':ZONES[p.zone].name.toLocaleUpperCase('tr')}</small><strong>Dijital parsel <span>${id.split('-').slice(1).join('·')}</span></strong><span>${fmt(p.area)} m² · ${esc(p.district)}</span><b>${fmt(p.listing||p.value)} ◈ <em>${p.arsa?'İmarlı arsa':p.fringe?'Gelişme sınırı':'Tarla'}</em></b></span><span class="card-chevron">›</span></button>`;}).join(''):`<div class="empty"><span>${icon(tab==='mine'?'grid':'pin')}</span><strong>${tab==='mine'?'İlk arsan seni bekliyor.':tab==='market'?'Henüz satış ilanı yok.':'Biraz daha yakından bakalım.'}</strong><p>${tab==='explore'?'Bir şehir seç, mahalle ölçeğine yakınlaş ve renkli bir parsele dokun.':tab==='market'?'Sahip olduğun bir parseli satışa çıkarabilirsin.':'Haritayı keşfederek ilk dijital parselini seç.'}</p><button id="discover" class="text-button">${tab==='explore'?'İzmir’i keşfet':'Haritaya dön'} ${icon('arrow')}</button></div>`;
 if(ids.length>30)$('#parcel-list').insertAdjacentHTML('beforeend','<p class="source-note">İlk 30 parsel gösteriliyor. Diğerlerini doğrudan haritadan seçebilirsin.</p>');
 document.querySelectorAll('[data-parcel]').forEach(b=>b.onclick=()=>select(b.dataset.parcel,true));document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;draw();});$('#discover')?.addEventListener('click',()=>{tab='explore';filter='all';map?.go(HOTSPOTS[1].loc);draw();});$('#next-week')?.addEventListener('click',()=>{modal('<h2>Yeni bir oyun haftası.</h2><p>Bölge planları yeniden değerlendirilecek. Bazı söylentiler onaylanabilir, bazıları ertelenebilir. Bu adım gerçek zamanı veya belediye kararlarını temsil etmez.</p><button id="advance" class="primary">Haftayı ilerlet</button>');$('#advance').onclick=()=>{state.week++;save();map?.render(state);draw();$('#modal').close();toast(`${state.week+1}. oyun haftasına geçildi.`);};});
}
function select(id,fly=false){selected=id;map?.select(id,fly);draw();if(innerWidth<760)$('#side').scrollIntoView({behavior:'smooth',block:'start'});}
function detail(){const p=get(selected),zone=ZONES[p.zone],r=rumor(p,state.week),owned=mine(p),buyable=!p.owner||p.listing;
 $('#side').innerHTML=`<button class="back" id="back">← Keşfe dön</button><div class="detail-visual" style="--parcel:${zone.color}"><span class="detail-map-grid"></span><span class="parcel-art ${p.zone}"><i></i><b>${p.building?BUILDINGS[p.building].icon:p.zone==='field'?'🌾':'⌂'}</b></span><span class="zone-pill">${zone.name}</span></div><div class="eyebrow">DİJİTAL PARSEL · ${p.id}</div><h2>${p.building?BUILDINGS[p.building].name:p.zone==='field'?'Toprağında ihtimal var.':'Hayalin için bir yer.'}</h2><p class="coordinates">${icon('pin')} ${p.lat.toFixed(5)}° K, ${p.lon.toFixed(5)}° D <button id="show-map">Haritada gör ↗</button></p>
 <div class="facts"><div><small>Parsel alanı ≈</small><strong>${fmt(p.area)} m²</strong></div><div><small>Nitelik</small><strong>${p.arsa?'Arsa (imarlı)':p.fringe?'Tarla · gelişme sınırı':'Tarla / arazi'}</strong></div><div><small>Oyun plan türü</small><strong>${zone.plan}</strong></div><div><small>Kat izni</small><strong>${zone.floors?`En fazla ${zone.floors} kat`:'Yapı izni yok'}</strong></div><div><small>İş yeri izni</small><strong>${zone.commercial?'İzin var':'İzin yok'}</strong></div><div><small>Yerleşim</small><strong>${esc(p.district)}</strong></div></div>
 <p class="source-note">${p.context.inUrban?'Yerleşik alan sınırı içinde':'Yerleşik alan sınırı dışında'} · ilçe merkezine ${(p.context.distance/1000).toFixed(1)} km · ilçe nüfusu ${fmt(p.context.pop)} (TÜİK ADNKS). İmar sınıfı bu gerçek verilerden türetilmiş oyun kurgusudur.</p>
 <div class="rumor ${p.base==='field'?'':'confirmed'}"><div><span>✧</span><small>${r.state}</small></div><strong>${r.title}</strong><p>${r.text}</p></div>
 ${p.building?`<button id="model-preview" class="secondary">${icon('home')} Yapıyı 3D incele</button><div class="building-status">${BUILDINGS[p.building].icon} ${BUILDINGS[p.building].name} <b>${p.building==='farm'?'Tarım kullanımı':p.level+' / '+zone.floors+' kat'}</b></div>`:''}
 <div id="actions">${owned?(!p.building?`<h3>Arsana hayat kat</h3><div class="build-grid">${Object.entries(BUILDINGS).map(([key,b])=>`<button data-build="${key}" ${canBuild(p,key)?'':'disabled'} title="${canBuild(p,key)?b.name:'İmar planı bu kullanıma izin vermiyor'}"><span>${b.icon}</span><strong>${b.name}</strong><small>${canBuild(p,key)?fmt(b.cost)+' ◈':'İzin gerekli'}</small></button>`).join('')}</div>`:p.building!=='farm'&&p.level<zone.floors?`<button class="primary" id="upgrade">Bir kat ekle <span>${fmt(upgradePrice(p))} ◈</span></button>`:'')+`<button class="secondary" id="list">${icon('shop')} ${p.listing?'İlanı kaldır':'Satışa çıkar'}</button>`:buyable?`<div class="price-row"><span>${p.listing?'İlan fiyatı':'Dijital parsel bedeli'}</span><strong>${fmt(p.listing||p.value)} <small>◈</small></strong></div><button class="primary" id="buy">${api?'Dijital parseli satın al':'Demo jetonuyla satın al'} ${icon('arrow')}</button>`:'<div class="empty">Bu dijital parsel başka bir oyuncuya ait ve satışta değil.</div>'}</div><p class="source-note" id="detail-note"></p>`;
 // Keep the product language Turkish.
 $('#detail-note').textContent=(owned?'Bu dijital parsel sana ait. ':'')+'Sınırlar, fiyatlar, izinler ve söylentiler oyun içindir. Gerçek tapu veya belediye verisi değildir.';
 $('#model-preview')?.addEventListener('click',async()=>{modal('<h2>Arsanda küçük bir hayat.</h2><div id="model-view" style="height:300px;border-radius:14px;overflow:hidden"></div><p class="source-note">Temsili oyun modeli · Sürükleyerek döndür, kaydırarak yakınlaş.</p>');try{const {createWorld}=await import('./world.js');if(!$('#modal').open||!$('#model-view'))return;const preview=createWorld($('#model-view'),()=>{});preview.render({plots:[{id:1,x:0,z:0,type:p.building==='shop'?'cafe':p.building,level:Math.max(1,p.level),floors:p.level,onlyFarm:p.building==='farm',owner:'you'}]});preview.focus(1);preview.zoom(.4);$('#modal').addEventListener('close',()=>preview.dispose(),{once:true});}catch{toast('3D model bu tarayıcıda açılamadı.');}});
 $('#back').onclick=()=>{selected=null;map?.select(null);draw();};$('#show-map').onclick=()=>{map?.select(selected,true);$('.map-panel').scrollIntoView({behavior:'smooth'});};$('#buy')?.addEventListener('click',()=>confirm('buy',p.listing||p.value));$('#upgrade')?.addEventListener('click',()=>confirm('upgrade',upgradePrice(p)));document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>confirm('build',BUILDINGS[b.dataset.build].cost,{type:b.dataset.build}));$('#list')?.addEventListener('click',()=>{if(p.listing){act('unlist');return;}modal(`<h2>Yeni bir hikâyeye yer aç.</h2><p>İlan bedelini oyun jetonu olarak belirle.</p><form id="listing"><label>Satış fiyatı<input name="price" type="number" min="100" max="1000000" step="1" required value="${p.value}"></label><button class="primary">İlanı yayınla</button></form>`);$('#listing').onsubmit=e=>{e.preventDefault();act('list',{price:Number(new FormData(e.target).get('price'))});};});
}
function confirm(action,cost,data={}){if(api&&!user){account();return;}modal(`<span class="modal-icon">${icon(action==='buy'?'grid':'home')}</span><h2>${action==='buy'?'Hikâyen burada başlasın.':'Arsana yeni bir hayat.'}</h2><p>${fmt(cost)} oyun jetonu kullanılacak. İşlem sonrası bakiye: <strong>${fmt(state.balance-cost)} ◈</strong>.</p><p class="source-note">${api?'Sanal oyun mülkü satın alıyorsun.':'Ücretsiz demo; gerçek para veya tapu devri yok.'}</p><button id="confirm" class="primary" ${state.balance<cost?'disabled':''}>${state.balance<cost?'Yetersiz bakiye':'Onayla ve devam et'} ${icon('arrow')}</button>`);$('#confirm').onclick=()=>act(action,data);}
async function request(path,data){const res=await fetch(api+path,{method:data?'POST':'GET',headers:{'Content-Type':'application/json',...(user?.token?{Authorization:'Bearer '+user.token}:{})},...(data?{body:JSON.stringify(data)}:{})});const body=await res.json();if(!res.ok)throw Error(body.error||'İşlem tamamlanamadı.');return body;}
async function refresh(){if(api){const result=await request('/world');if(result.version!==3)throw Error('Sunucu Dijital Arsam sürümüne güncellenmeli.');state={...result,balance:0};if(user){const me=await request('/me');state.balance=me.balance;}}map?.render(state);draw();}
async function act(action,data={}){if(busy||!available)return;busy=true;const buttons=[...document.querySelectorAll('#modal button,#actions button')];buttons.forEach(b=>b.disabled=true);try{if(api){await request('/action',{action,id:selected,...data});await refresh();}else{applyAction(state,'you',action,selected,data);save();map?.render(state);draw();}$('#modal').close();toast({buy:'Bu dijital parsel artık senin. 🌱',build:'Arsana yeni bir hayat geldi!',upgrade:'Binana bir kat eklendi.',list:'İlanın yayınlandı.',unlist:'İlan kaldırıldı.'}[action]);}catch(e){toast(e.message);buttons.forEach(b=>b.disabled=false);}finally{busy=false;}}
function account(){if(!api){modal('<h2>Hoş geldin, komşu.</h2><p>Ücretsiz demo ilerlemen bu tarayıcıda saklanır. Ortak dünya ve gerçek hesaplar, sunucu bağlandığında açılır. Eski Mahalle demo kaydın ayrıca korunur.</p><button id="close-demo" class="primary">Keşfetmeye devam et</button>');$('#close-demo').onclick=()=>$('#modal').close();return;}if(user){modal(`<h2>Merhaba, ${esc(user.name)}.</h2><button id="logout" class="secondary">Çıkış yap</button>`);$('#logout').onclick=async()=>{await request('/logout',{}).catch(()=>{});user=null;sessionStorage.removeItem('mahalle-user');$('#modal').close();refresh().catch(e=>toast(e.message));};return;}modal('<h2>Dijital Arsam’a katıl.</h2><form id="auth"><label>İsim (yeni hesap)<input name="name" maxlength="40" autocomplete="nickname"></label><label>E-posta<input name="email" type="email" required autocomplete="email"></label><label>Şifre<input name="password" type="password" minlength="10" required autocomplete="current-password"></label><button class="primary" value="login">Giriş yap</button><button class="secondary" value="register">Yeni hesap oluştur</button></form>');$('#auth').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{user=await request('/auth/'+e.submitter.value,Object.fromEntries(new FormData(e.target)));sessionStorage.setItem('mahalle-user',JSON.stringify(user));$('#modal').close();await refresh();}catch(err){toast(err.message);}finally{e.submitter.disabled=false;}};}
$('#account').onclick=account;$('#wallet').onclick=()=>{if(!api){modal('<h2>Biraz daha hayal kur.</h2><p>Ücretsiz demo jetonları ekle. Gerçek ödeme yapılmaz.</p><button class="primary" id="credit">10.000 demo jetonu ekle</button>');$('#credit').onclick=()=>{state.balance+=10000;save();draw();$('#modal').close();};return;}if(!user)return account();modal('<h2>Oyun jetonu al.</h2><p>1.000 jeton · 5,00 €<br>Oyun jetonları nakde çevrilemez.</p><button class="primary" id="checkout">Stripe ile devam et</button>');$('#checkout').onclick=async e=>{e.target.disabled=true;try{const {url}=await request('/checkout',{});location.href=url;}catch(err){toast(err.message);e.target.disabled=false;}};};
function normalize(s){return s.toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i');}
$('#search-form').onsubmit=e=>{e.preventDefault();const q=$('#search').value.trim(),coord=q.match(/^(-?\d+(?:\.\d+)?)\s*[,;]\s*(-?\d+(?:\.\d+)?)$/);if(coord){const lat=+coord[1],lon=+coord[2];if(lon<25.5||lon>45||lat<35.7||lat>42.3)return toast('Türkiye içinde enlem, boylam gir.');map?.go([lon,lat],16);$('#results').hidden=true;return;}if(q.length<2)return;const terms=normalize(q).split(/\s+/);const results=places.filter(p=>terms.every(t=>normalize(p.label).includes(t))).slice(0,15);$('#results').hidden=false;$('#results').innerHTML=results.length?results.map((p,i)=>`<button data-result="${i}">${icon('pin')}<span><strong>${esc(p.name)}</strong><small>${esc(p.label)}</small></span>↗</button>`).join(''):'<p>İl veya ilçe bulunamadı. Mahalle isimlerini haritada yakınlaşarak görebilirsin; koordinatla da gidebilirsin.</p>';$('#results').querySelectorAll('button').forEach(b=>b.onclick=()=>{const p=results[+b.dataset.result];region=p.name;map?.go(p.loc,p.zoom);$('#search').value=p.label;$('#results').hidden=true;});};
$('#search').onkeydown=e=>{if(e.key==='Escape')$('#results').hidden=true;};document.querySelectorAll('[data-hot]').forEach(b=>b.onclick=()=>{const p=HOTSPOTS[+b.dataset.hot];region=p.name;map?.go(p.loc);});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{map?.mode(b.dataset.mode);document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;selected=null;map?.select(null);draw();});$('#turkey').onclick=()=>map?.home();$('#grid').onclick=e=>{const on=map?.grid();e.currentTarget.setAttribute('aria-pressed',String(on));toast(on?'Dijital parseller gösteriliyor.':'Parseller gizlendi.');};$('#tilt').onclick=()=>map?.tilt();
$('#help').onclick=()=>modal(`<h2>Gerçek harita.<br>Dijital bir oyun.</h2><ol><li>İl veya ilçe ara. Sokak ve mahalleleri görmek için yakınlaş.</li><li>Renkli bir oyun parseli seç; şeklini, alanını, imar ve kat iznini incele.</li><li>Tarım, konut veya ticaret iznine uygun bir kullanım seç.</li><li>Demo takviminde haftayı ilerleterek oyun kararlarını takip et.</li><li>Arsanı jeton karşılığında satışa çıkar.</li></ol><p>Parseller her blokta farklı büyüklük ve şekilde üretilir; üçgen, çok köşeli veya geniş tarla olabilirler ve kara üzerinde boşluk bırakmadan birleşirler. Sınırlar tapu sınırı değildir, yol ve binalarla çakışabilir. İmarlı arsa mı yoksa tarla mı olduğu gerçek yerleşik alan verisi, ilçe nüfusu ve yoğunluğundan hesaplanır; belediyenin imar planı değildir. İşlemler gerçek taşınmaz hakkı vermez.</p><p class="source-note">Harita: <a href="https://openfreemap.org/" target="_blank" rel="noopener">OpenFreeMap / OpenStreetMap</a>. Uydu: <a href="https://www.arcgis.com/home/item.html?id=10df2279f9684e4a9f6a7f08febac2a9" target="_blank" rel="noopener">Esri World Imagery</a>. Sınır ve yerleşik alanlar: Natural Earth. İlçe nüfusu: TÜİK ADNKS derlemesi. İl ve ilçe araması yerel veriyle çalışır; mahalle adı araması henüz yoktur.</p>`);
draw();
try{const responses=await Promise.all([fetch('./data/land.json'),fetch('./data/places.json'),fetch('./data/landuse.json')]);if(responses.some(r=>!r.ok))throw Error('Coğrafi veri yüklenemedi.');const [land,cities,landuse]=await Promise.all(responses.map(r=>r.json()));if(!setLand(land))throw Error('Kara sınırı verisi okunamadı.');setLanduse(landuse);const boundary=landFeature();places=cities.flatMap(c=>[{name:c.name,label:c.name+' · İl',loc:[+c.longitude,+c.latitude],zoom:11},...(c.towns||[]).filter(t=>Number.isFinite(+t.longitude)&&Number.isFinite(+t.latitude)).map(t=>({name:t.name,label:t.name+' / '+c.name+' · İlçe',loc:[+t.longitude,+t.latitude],zoom:14.5}))]);available=true;map=createMap($('#map'),boundary,{status:s=>$('#map-status').textContent=s,select,visible:ids=>{visible=ids;if(!selected&&tab==='explore')draw();},error:msg=>{$('#map-error').hidden=false;$('#map-error').textContent=msg;},ready:()=>{$('#map-error').hidden=true;}});map.render(state);if(api)await refresh();}catch(e){available=false;$('#map-error').hidden=false;$('#map-error').textContent=e.message+' Sayfayı yenileyerek tekrar dene.';$('#map-status').textContent='Harita bağlantısı bekleniyor';}
if(api)setInterval(()=>{if(!busy&&!$('#modal').open)refresh().catch(e=>toast(e.message));},20000);
